# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: DB Setup
      run: >
        sh -c "python src/manage.py makemigrations authentication &&
             python src/manage.py migrate &&
             python src/manage.py shell -c 'from authentication.models import CustomUser;CustomUser.objects.create_user(email=\"im@paroham.in\",first_name=\"im\", last_name=\"parham\", level=\"AD\",password=\"dr0w.Ssap\") if not CustomUser.objects.filter(email=\"im@paroham.in\").exists() else print(\"exists\")' &&
             #python src/manage.py shell -c 'from authentication.models import CustomUser;a=CustomUser.objects.get(email=\"im@paroham.in\");print(\"email-im@paroham.in password-dr0w.Ssap\") if a.email ==\"im@paroham.in\" else CustomUser.objects.create_user(email=\"im@paroham.in\",first_name=\"im\", last_name=\"parham\", level=\"AD\",password=\"dr0w.Ssap\")' &&
             python src/manage.py runserver 0.0.0.0:8000"
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
